#!/usr/bin/env python3
"""Seed all JSON data files with current dashboard data."""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from db_init import save, today, DATA_DIR, ensure_data_dir

def seed():
    ensure_data_dir()
    T = today()
    save("meta", {"title":"AI Datacenter Electricity Supply - Investment Landscape","subtitle":"Global analysis of power infrastructure for AI datacenters","last_updated":T,"sources":"Company SEC filings, earnings reports, IEA, Goldman Sachs Research, S&P Global, Wood Mackenzie, press releases"})
    save("kpi_metrics", [
        {"key":"dc_capacity","label":"Total Planned DC Capacity","value":"~96 GW","subtitle":"Announced by hyperscalers by 2030","numeric":96,"highlight":True,"updated":T},
        {"key":"hscaler_capex","label":"2026 Hyperscaler CapEx","value":"$600B+","subtitle":"~75% tied to AI infrastructure","numeric":600,"highlight":True,"updated":T},
        {"key":"grid_queue","label":"US Grid Queue Backlog","value":"2,600 GW","subtitle":"Median wait: ~5 years","numeric":2600,"highlight":True,"updated":T},
        {"key":"transformer_lead","label":"Power Transformer Lead","value":"128 wks","subtitle":"30% supply deficit in 2025","numeric":128,"highlight":True,"updated":T},
        {"key":"gev_backlog","label":"GE Vernova Turbine Backlog","value":"100 GW","subtitle":"Sold out through 2030","numeric":100,"highlight":False,"updated":T},
        {"key":"btm_projects","label":"Behind-the-Meter Projects","value":"48 GW","subtitle":"~40 projects announced by end 2025","numeric":48,"highlight":False,"updated":T}
    ])
    print("Seeded: meta, kpi_metrics")

    # NOTE: companies.json is now maintained directly (84 companies, 5-category taxonomy).
    # This seed provides a minimal fallback. See build_companies.py for the full database.
    # Categories: software, hyperscaler, electricity, dc_hardware, semiconductor_fab
    save("companies", [
        {"ticker":"MSFT","name":"Microsoft","sector":"hyperscaler","sub_sector":"Integrated Cloud Operators","rating":"STRONG_BUY","emoji":"\U0001f7e2","exposure":"Operator","report":"reports/MSFT_Microsoft.html","public":True},
        {"ticker":"AMZN","name":"Amazon / AWS","sector":"hyperscaler","sub_sector":"Integrated Cloud Operators","rating":"BUY","emoji":"\U0001f7e1","exposure":"Operator","report":"reports/AMZN_Amazon.html","public":True},
        {"ticker":"GOOGL","name":"Google / Alphabet","sector":"hyperscaler","sub_sector":"Integrated Cloud Operators","rating":"BUY","emoji":"\U0001f7e1","exposure":"Operator","report":"reports/GOOGL_Alphabet.html","public":True},
        {"ticker":"META","name":"Meta","sector":"hyperscaler","sub_sector":"Integrated Cloud Operators","rating":"BUY","emoji":"\U0001f7e1","exposure":"Operator","report":"reports/META_Meta.html","public":True},
        {"ticker":"ORCL","name":"Oracle","sector":"hyperscaler","sub_sector":"Integrated Cloud Operators","rating":"HOLD","emoji":"\U0001f7e0","exposure":"Operator","report":"reports/ORCL_Oracle.html","public":True},
        {"ticker":"CRWV","name":"CoreWeave","sector":"hyperscaler","sub_sector":"GPU Cloud Providers","rating":"SELL","emoji":"\U0001f534","exposure":"100%","report":"reports/CRWV_CoreWeave.html","public":True},
        {"ticker":"NVDA","name":"NVIDIA","sector":"dc_hardware","sub_sector":"GPUs & AI Accelerators","rating":"STRONG_BUY","emoji":"\U0001f7e2","exposure":"80%+","report":"reports/NVDA_Nvidia.html","public":True},
        {"ticker":"AMD","name":"AMD","sector":"dc_hardware","sub_sector":"GPUs & AI Accelerators","rating":"BUY","emoji":"\U0001f7e1","exposure":"50%+","report":"reports/AMD_AMD.html","public":True},
        {"ticker":"AVGO","name":"Broadcom","sector":"dc_hardware","sub_sector":"GPUs & AI Accelerators","rating":"HOLD","emoji":"\U0001f7e0","exposure":"40%+","report":"reports/AVGO_Broadcom.html","public":True},
        {"ticker":"TSM","name":"TSMC","sector":"semiconductor_fab","sub_sector":"Foundries","rating":"BUY","emoji":"\U0001f7e1","exposure":"50%+","report":"reports/TSM_TSMC.html","public":True},
        {"ticker":"GEV","name":"GE Vernova","sector":"electricity","sub_sector":"Gas Turbine OEMs","rating":"STRONG_BUY","emoji":"\U0001f7e2","exposure":"25-30%","report":"reports/GEV_GE_Vernova.html","public":True},
        {"ticker":"CEG","name":"Constellation Energy","sector":"electricity","sub_sector":"Nuclear Utilities","rating":"BUY","emoji":"\U0001f7e1","exposure":"30-40%","report":"reports/CEG_Constellation.html","public":True},
        {"ticker":"SMR","name":"NuScale Power","sector":"electricity","sub_sector":"SMR Developers","rating":"HOLD","emoji":"\U0001f7e0","exposure":"Pre-revenue","report":"reports/SMR_NuScale.html","public":True},
        {"ticker":"OKLO","name":"Oklo","sector":"electricity","sub_sector":"SMR Developers","rating":"HOLD","emoji":"\U0001f7e0","exposure":"Pre-revenue","report":"reports/OKLO_Oklo.html","public":True}
    ])
    print("Seeded: companies")

    save("hyperscaler_buildouts", [
        {"ticker":"MSFT","name":"Microsoft","capex_2024":56,"capex_2025":78,"capex_2026e":80,"current_power":"~2 GW added FY25","target_power":"34 GW contracted clean","target_year":"2027-2030","energy_badges":["Nuclear PPA (TMI)","Solar"],"energy_types":["nuclear","solar"],"detail_title":"Microsoft - Crane Clean Energy Center","detail_html":"20-year PPA with Constellation to restart Three Mile Island Unit 1 (835 MW). $1.6B investment, backed by $1B DOE loan guarantee. ~80% staffed, targeting 2027 restart. Also froze 1.5 GW of near-term self-build and cancelled ~2 GW of leases in 2025.","detail_source":"Source: Constellation Energy, Microsoft Azure Blog","chart_current_gw":2,"chart_target_gw":34,"updated":T},
        {"ticker":"AMZN","name":"Amazon / AWS","capex_2024":75,"capex_2025":100,"capex_2026e":200,"current_power":"~15 GW (Q3 2025)","target_power":"31 GW","target_year":"End 2027","energy_badges":["Nuclear (Susquehanna)","Solar","Gas"],"energy_types":["nuclear","solar","gas"],"detail_title":"Amazon - Multi-GW Indiana & Virginia","detail_html":"$15B investment in Northern Indiana adding ~2.4 GW. Virginia Mattermeade project: 11 two-story DC buildings targeting 770 MW by 2027. $50B for US gov AI infrastructure adding 1.3 GW. AWS power could reach 31 GW by end-2027.","detail_source":"Source: AWS press releases, Benzinga","chart_current_gw":15,"chart_target_gw":31,"updated":T},
        {"ticker":"GOOGL","name":"Google / Alphabet","capex_2024":33,"capex_2025":75,"capex_2026e":75,"current_power":"Growing rapidly","target_power":"2.7 GW (Michigan alone)","target_year":"2026-2028","energy_badges":["Nuclear (Duane Arnold)","1.6 GW Solar","Fusion PPA (CFS)"],"energy_types":["nuclear","solar","fusion"],"detail_title":"Google - Nuclear + Fusion Pioneer","detail_html":"First corporate fusion PPA (CFS, July 2025). 2.7 GW Michigan campus. Duane Arnold nuclear restart via NextEra (615 MW, 25yr). 1.6 GW solar PPAs. GCP revenue growth 50%+.","detail_source":"Source: Google announcements, NextEra filings","chart_current_gw":5,"chart_target_gw":25,"updated":T},
        {"ticker":"META","name":"Meta","capex_2024":37,"capex_2025":72.2,"capex_2026e":125,"current_power":"~1.3M GPUs","target_power":"5 GW (Hyperion)","target_year":"2030","energy_badges":["6.6 GW Nuclear deals","Solar PPAs"],"energy_types":["nuclear","solar"],"detail_title":"Meta - 5 GW Hyperion (Louisiana)","detail_html":"World's largest planned DC: 5 GW total, Phase 1 = 2 GW by 2030, interim 1.5 GW by end-2027. $27B JV with Blue Owl Capital. Secured 6.6 GW of nuclear power from TerraPower, Oklo, and Vistra. Also Prometheus (Ohio) due online 2026.","detail_source":"Source: IEEE Spectrum, Meta announcements","chart_current_gw":1.5,"chart_target_gw":5,"updated":T},
        {"ticker":"ORCL","name":"Oracle / Stargate","capex_2024":6.9,"capex_2025":21.2,"capex_2026e":35,"current_power":"Growing","target_power":"7 GW (Stargate total)","target_year":"2027-2029","energy_badges":["Grid + BTM","Gas"],"energy_types":["grid","gas"],"detail_title":"Oracle/Stargate - 7 GW Multi-Site","detail_html":"4.5 GW new capacity agreement with OpenAI across 5 new sites. Combined with Abilene flagship and CoreWeave projects = ~7 GW planned, $400B+ investment over 3 years. OCI revenue projected: $18B FY26 to $144B FY30.","detail_source":"Source: OpenAI blog, Oracle earnings","chart_current_gw":1,"chart_target_gw":7,"updated":T},
        {"ticker":"CRWV","name":"CoreWeave","capex_2024":5,"capex_2025":16,"capex_2026e":32,"current_power":"0.85 GW","target_power":"3.1 GW contracted, +5 GW","target_year":"2027 / 2030","energy_badges":["Grid","Gas"],"energy_types":["grid","gas"],"detail_title":"CoreWeave - Rapid Scale","detail_html":"850 MW active power across 43 DCs (end 2025). Contracted 3.1 GW, virtually all online by 2027. Targeting 1.7 GW active by end-2026. $6B Pennsylvania campus (100-300 MW). Adding 5 GW more by 2030. CapEx doubling to $30-35B in 2026.","detail_source":"Source: CoreWeave blog, DCD","chart_current_gw":0.85,"chart_target_gw":8.1,"updated":T},
        {"ticker":"XAI","name":"xAI (Colossus)","capex_2024":3,"capex_2025":8,"capex_2026e":15,"current_power":"~0.45 GW live","target_power":"2 GW","target_year":"Q2 2027","energy_badges":["Gas turbines (Solaris)"],"energy_types":["gas"],"detail_title":"xAI - Colossus Memphis","detail_html":"Expanded from 250 MW to 2 GW across three buildings. Solaris Energy Infrastructure supplying ~400 MW gas turbines now, targeting 1.1 GW by Q2 2027. 200 MW live within 6 months of site acquisition. Acquired former Duke Energy plant (245 MW).","detail_source":"Source: SemiAnalysis, NextBigFuture","chart_current_gw":0.45,"chart_target_gw":2,"updated":T}
    ])
    print("Seeded: hyperscaler_buildouts")

    save("power_suppliers", [
        {"company":"GE Vernova","ticker":"GEV","segment":"Gas Turbine OEM","exposure":"High - Electrification segment","deals":"$2.4B DC equipment orders Q1 26 alone","backlog":"100 GW turbine backlog, targeting 110 GW by YE 26. $163B total backlog","outlook":"Rev $44.5-45.5B in 2026. Sold out through 2030. Backlog to $200B by 2027","report":"reports/GEV_GE_Vernova.html","updated":T},
        {"company":"Constellation Energy","ticker":"CEG","segment":"Nuclear Utility","exposure":"High - Nuclear PPAs","deals":"Microsoft TMI (835 MW, 20yr), Meta Clinton (1.1 GW, 20yr), CyrusOne 380 MW","backlog":"55 GW total capacity (post-Calpine). Largest US nuclear fleet","outlook":"Rev ~$30B in 2026. 13%+ EPS growth through 2030. Calpine 20%+ EPS accretive","report":"reports/CEG_Constellation_Energy.html","updated":T},
        {"company":"Vistra Energy","ticker":"VST","segment":"IPP / Nuclear","exposure":"High - Nuclear + Gas","deals":"Meta: 2,609 MW from 3 nuclear plants. Cogentrix acquisition ($4.7B, 5.5 GW gas)","backlog":"Large nuclear + gas fleet across PJM","outlook":"Long-term PPA discussions with hyperscalers for new gas plants","report":"reports/VST_Vistra.html","updated":T},
        {"company":"NextEra Energy","ticker":"NEE","segment":"Utility / Renewables","exposure":"High - Solar + Nuclear","deals":"Google: Duane Arnold restart (615 MW, 25yr). Meta: 2.5 GW clean (11 PPAs). 10 GW gas in TX/PA","backlog":"Largest global renewables developer","outlook":"Strong contracted pipeline through 2028","report":"reports/NEE_NextEra_Energy.html","updated":T},
        {"company":"AES Corporation","ticker":"AES","segment":"Utility / Renewables","exposure":"Medium-High","deals":"Part of NVIDIA/Emerald AI initiative","backlog":"Large renewables + storage portfolio","outlook":"Partnering on flexible AI factories as grid assets","report":None,"updated":T},
        {"company":"Siemens Energy","ticker":"ENR.DE","segment":"Gas Turbine OEM","exposure":"High - Gas Services","deals":"Record gas turbine orders for DC power","backlog":"EUR 138B order backlog. Nearly doubled turbine sales: 100 to 194 units in 2025","outlook":"Record fiscal year. Mid-term outlook raised. Backlog extends 5+ years","report":"reports/ENR_Siemens_Energy.html","updated":T},
        {"company":"Mitsubishi Power","ticker":"7011.T","segment":"Gas Turbine OEM","exposure":"High","deals":"US market turbine orders","backlog":"48 turbine backlog. Doubling manufacturing capacity","outlook":"Backlog scheduled through 2028-2030","report":None,"updated":T},
        {"company":"ExxonMobil","ticker":"XOM","segment":"BTM Gas Power","exposure":"New / Growing","deals":"1.5 GW dedicated gas plant (off-grid). 1.2 GW JV with NextEra","backlog":"Entering DC power market","outlook":"Bypasses grid queue via behind-the-meter. 2,500-acre campus in SE US","report":None,"updated":T},
        {"company":"Enchanted Rock","ticker":None,"segment":"Modular Gas Gen","exposure":"High","deals":"Meta El Paso: 813 modular generators stacked","backlog":"Modular gas-fired microgrids","outlook":"Key enabler of fast BTM deployments","report":None,"updated":T},
        {"company":"Solaris Energy Infra","ticker":None,"segment":"BTM Gas Power","exposure":"Very High","deals":"xAI Colossus: ~400 MW active, 1.1 GW by Q2 27","backlog":"600 MW fleet currently","outlook":"Primary power supplier for xAI rapid buildout","report":None,"updated":T}
    ])
    print("Seeded: power_suppliers")

    save("hardware_suppliers", [
        {"company":"Eaton","ticker":"ETN","category":"Power Distribution","product":"UPS, switchgear, PDUs, transformers","relevance":"End-to-end DC power distribution. $1.5B incremental capacity investment","metrics":"New SC transformer plant by 2027. $340M expansion","report":"reports/ETN_Eaton.html","updated":T},
        {"company":"Schneider Electric","ticker":"SU.PA","category":"Power Distribution","product":"EcoStruxure platform, UPS, PDUs, switchgear","relevance":"18% share of DC switchgear market. End-to-end energy management","metrics":"Mkt Cap: ~EUR 154B","report":"reports/SU_Schneider_Electric.html","updated":T},
        {"company":"Vertiv","ticker":"VRT","category":"Power & Cooling","product":"UPS, thermal management, power conversion","relevance":"Critical DC infrastructure. Liquid cooling solutions","metrics":"Major beneficiary of DC buildout","report":"reports/VRT_Vertiv.html","updated":T},
        {"company":"Hitachi Energy","ticker":"6501.T","category":"Transformers","product":"Large power transformers, grid equipment","relevance":"Expanding VA and PA transformer manufacturing","metrics":"Lead times: 128 weeks (power), 144 weeks (GSU)","report":None,"updated":T},
        {"company":"onsemi","ticker":"ON","category":"SiC Power Electronics","product":"SiC MOSFETs, power modules, vertical power delivery","relevance":"~25% SiC market share. AI accelerator power delivery modules","metrics":"Rev ~$9B FY26E. Transitioned to 200mm SiC wafers (80% yield gain)","report":"reports/ON_onsemi.html","updated":T},
        {"company":"Wolfspeed","ticker":"WOLF","category":"SiC Substrates","product":"SiC wafers, MOSFETs, Gen 4 platform","relevance":"~11% SiC market share. Supplies wafers to Infineon et al","metrics":"300mm SiC wafer breakthrough. Restructuring underway","report":"reports/WOLF_Wolfspeed.html","updated":T},
        {"company":"Infineon","ticker":"IFX.DE","category":"Power Semiconductors","product":"SiC & Si power modules, IGBTs","relevance":"~15% SiC market share. Key supplier for inverters/converters","metrics":"Long-term Wolfspeed wafer supply agreement","report":"reports/IFX_Infineon.html","updated":T},
        {"company":"STMicroelectronics","ticker":"STM","category":"Power Semiconductors","product":"SiC MOSFETs, diodes","relevance":"~35% SiC market share (leader). DC power conversion","metrics":"Largest SiC revenue base globally","report":"reports/STM_STMicroelectronics.html","updated":T},
        {"company":"Aehr Test Systems","ticker":"AEHR","category":"Test Equipment","product":"Wafer-level & package-level burn-in","relevance":"Testing SiC devices + AI processors for DCs","metrics":"$37.2M quarterly bookings (3.5x book-to-bill). Hyperscaler AI processor orders","report":"reports/AEHR_Aehr_Test.html","updated":T},
        {"company":"Fluence Energy","ticker":"FLNC","category":"Battery Storage","product":"BESS systems, grid-scale storage","relevance":"DC peak shaving, grid stabilization","metrics":"Global BESS market: $76.7B (2025) to $172.2B (2030)","report":"reports/FLNC_Fluence.html","updated":T},
        {"company":"Tesla Energy","ticker":"TSLA","category":"Battery Storage","product":"Megapack BESS","relevance":"DC backup power, grid-scale storage","metrics":"Leading utility-scale BESS deployments","report":None,"updated":T}
    ])
    print("Seeded: hardware_suppliers")

    save("nuclear_tracker", [
        {"company":"NuScale Power","ticker":"SMR","technology":"Light-water SMR","capacity":"77 MWe per module","nrc_status":"Full NRC design certification (Jan 2023) - only SMR with this","first_commercial":"2029-2030 (Idaho site cancelled; seeking new)","dc_partners":"Exploring DC applications","report":"reports/SMR_NuScale.html","updated":T},
        {"company":"Oklo","ticker":"OKLO","technology":"Fast reactor (Aurora)","capacity":"15-50 MWe","nrc_status":"License application expected 2026","first_commercial":"Late 2027 / Early 2028 at INL","dc_partners":"Meta (part of 6.6 GW deal)","report":"reports/OKLO_Oklo.html","updated":T},
        {"company":"TerraPower","ticker":None,"technology":"Natrium (sodium-cooled)","capacity":"345 MWe","nrc_status":"Construction started (Wyoming)","first_commercial":"2030-2031","dc_partners":"Meta (part of 6.6 GW deal)","report":None,"updated":T},
        {"company":"Kairos Power","ticker":None,"technology":"Fluoride salt-cooled (Hermes)","capacity":"140 MWe (commercial)","nrc_status":"Construction permit for Hermes test reactor (Dec 2023)","first_commercial":"2030+","dc_partners":"Google (agreement signed)","report":None,"updated":T},
        {"company":"X-energy","ticker":"XE","technology":"HTGR (Xe-100)","capacity":"80 MWe per module","nrc_status":"NRC review underway, 18-mo target","first_commercial":"~2028-2029 (DOE demo)","dc_partners":"AWS partnership","report":None,"updated":T},
        {"company":"Last Energy","ticker":None,"technology":"Micro PWR","capacity":"20 MWe","nrc_status":"European pathway","first_commercial":"2026-2027 (Wales) - fastest timeline","dc_partners":"European DC operators","report":None,"updated":T}
    ])
    save("fusion_tracker", [
        {"company":"Commonwealth Fusion Systems (CFS)","technology":"Tokamak with high-temperature superconducting magnets (SPARC)","timeline":"Magnet ring completion: Summer 2026. First plasma (SPARC): 2027. Net power demo (Q>1): 2027. Commercial plant (ARC) at James River, VA: Early 2030s.","dc_connection":"Google signed first-of-kind corporate fusion PPA (July 2025)","funding":"$2B+ raised. Backed by Google, Bill Gates, Tiger Global","source":"Source: CFS website, TechCrunch, Wikipedia","updated":T},
        {"company":"Helion Energy","technology":"Field-reversed configuration (FRC) - pulsed fusion for direct electricity","timeline":"Polaris prototype: 150M C achieved (Feb 2026) - 75% of target. Orion (commercial reactor): Under construction. Microsoft PPA: Electricity delivery targeted 2028.","dc_connection":"Direct contract with Microsoft to supply fusion electricity starting 2028","funding":"$577M+ raised. Backed by Sam Altman (OpenAI), $500M from Sam Altman personally","source":"Source: TechCrunch (Feb 2026), Fortune","updated":T}
    ])
    save("haleu_constraint", {"title":"Critical Constraint: HALEU Fuel Supply","company":"Centrus Energy","ticker":"LEU","report":"reports/LEU_Centrus_Energy.html","description":"High-Assay Low-Enriched Uranium (HALEU) is required by most advanced reactors (Oklo, X-energy, Kairos). Centrus Energy (LEU) is the only US commercial HALEU producer. Revenue $449M, net income $78M (profitable). DOE contract extended through June 2026 (~$110M). HALEU market projected to grow from $0.26B to $6.2B by 2030. Analyst consensus: Buy, avg target $265.","updated":T})
    print("Seeded: nuclear_tracker, fusion_tracker, haleu_constraint")

    save("risks", [
        {"title":"Grid Interconnection Queue","severity":"high","description":"US queue at 2,600 GW backlog. Median wait: ~5 years, some projects facing 12-year delays. PJM and ERCOT most constrained.","impact":"Primary reason hyperscalers are pursuing behind-the-meter (BTM) solutions. ExxonMobil, Enchanted Rock, Solaris bypassing grid entirely.","mitigation":None,"source":"Source: RMI, Utility Dive, ENR","updated":T},
        {"title":"Power Transformer Shortage","severity":"high","description":"30% supply deficit for power transformers in 2025. Lead times: 128 weeks (power), 144 weeks (GSU). Prices up 60-70% since 2020.","impact":None,"mitigation":"Eaton ($340M SC plant by 2027), Siemens ($150M NC plant by 2027), Hitachi expanding VA/PA. Deficit expected to ease by 2030.","source":"Source: Wood Mackenzie, POWER Magazine","updated":T},
        {"title":"Gas Turbine Backlog","severity":"high","description":"GE Vernova sold out through 2030. Siemens backlog extends 5+ years. Mitsubishi doubling manufacturing but still catching up.","impact":"Hyperscalers using older aeroderivative models as bridge power. Order lead times pushing projects to 2028+.","mitigation":None,"source":"Source: GE Vernova, Siemens Energy earnings","updated":T},
        {"title":"HALEU Fuel Scarcity","severity":"medium","description":"Required for most SMRs (Oklo, X-energy, Kairos). Centrus (LEU) only commercial US source. Could delay SMR deployments beyond 2030.","impact":None,"mitigation":None,"source":"Source: DOE, NRC filings","updated":T},
        {"title":"Regulatory & Permitting Risk","severity":"medium","description":"Ireland, Netherlands blocking new DC connections. Parts of Virginia restricting growth. Pennsylvania governor threatened grid withdrawal. NRC reviews for SMRs taking 18+ months.","impact":None,"mitigation":None,"source":"Source: MultiState, industry reports","updated":T},
        {"title":"Hyperscaler Demand Pullback","severity":"medium","description":"Microsoft froze 1.5 GW self-build and cancelled 2 GW leases. Only ~5 GW of promised 16 GW for 2026 actually being built. AI inference efficiency gains could reduce power needs.","impact":None,"mitigation":"Overall CapEx still rising. Demand acceleration from Goldman Sachs revised up to 220% growth by 2030.","source":"Source: SemiAnalysis, Benzinga","updated":T}
    ])
    print("Seeded: risks")

    save("chart_data", {
        "demand_projections":{"type":"line","title":"Global Datacenter Power Demand Projections (GW)","source":"Sources: Goldman Sachs Research (Apr 2026), IEA Energy & AI Report","labels":["2023","2024","2025","2026E","2027E","2028E","2029E","2030E"],"datasets":[{"label":"Goldman Sachs Base (GW)","data":[55,62,80,92,110,130,145,165],"color":"#4C8BF5","fill":True,"tension":0.3},{"label":"Goldman Sachs High (GW)","data":[55,65,85,100,125,150,175,200],"color":"#A142F4","fill":False,"tension":0.3,"borderDash":[5,5]},{"label":"IEA Estimate (TWh to GW equiv)","data":[50,58,72,85,100,115,125,135],"color":"#34A853","fill":False,"tension":0.3,"borderDash":[3,3]}],"y_title":"Gigawatts (GW)","y_begin_zero":True},
        "energy_mix":{"type":"doughnut","title":"US Datacenter Energy Mix (2025)","source":"Source: S&P Global, Yale Clean Energy Forum","labels":["Natural Gas (43%)","Renewables (24%)","Coal (15%)","Nuclear (12%)","Other (6%)"],"data":[43,24,15,12,6],"colors":["#F9AB00","#34A853","#9E9E9E","#A142F4","#24C1E0"],"cutout":"55%"},
        "capex_trajectory":{"type":"bar","title":"Hyperscaler Capital Expenditure Trajectory ($B)","source":"Sources: Company earnings reports, SEC filings","full_width":True,"y_title":"Capital Expenditure ($B)","y_begin_zero":True},
        "clean_energy":{"type":"bar","title":"Hyperscaler Contracted Clean Energy (GW)","source":"Source: ESG Today, company announcements (end-2025 data)","labels":["Microsoft","Amazon","Google","Meta"],"data":[34.7,30,25,15],"colors":["#4C8BF5CC","#F9AB00CC","#34A853CC","#A142F4CC"],"indexAxis":"y","y_title":"GW"},
        "power_timeline":{"type":"bar","title":"Power Delivery Timeline - When Capacity Arrives","source":"Source: Company announcements, analyst estimates","labels":["Natural Gas (BTM)","Grid Expansion","Solar/Wind PPAs","Existing Nuclear PPAs","SMRs (Advanced Nuclear)","Fusion"],"datasets":[{"label":"Available Now","data":[48,5,15,10,0,0],"color":"#34A853CC"},{"label":"2027-2028","data":[20,10,20,5,0.5,0],"color":"#4C8BF5CC"},{"label":"2029-2030+","data":[15,15,25,5,5,0.5],"color":"#A142F4CC"}],"stacked":True,"indexAxis":"y","x_title":"Estimated GW"},
        "turbine_backlog":{"type":"bar","title":"Gas Turbine OEM Order Backlog Comparison","source":"Source: GE Vernova, Siemens Energy, MHI earnings reports (Q1 2026)","labels":["GE Vernova","Siemens Energy","Mitsubishi Power"],"data":[163,138,15],"colors":["#4C8BF5CC","#24C1E0CC","#F9AB00CC"],"tooltips":["$163B total / 100 GW turbines","EUR 138B total / 194 units sold in FY25","48 turbines, doubling capacity"],"y_title":"Backlog ($B / EUR B)"},
        "nuclear_ppas":{"type":"bar","title":"Key Nuclear PPAs for Datacenters","source":"Source: Company announcements, press releases","labels":["Meta-Vistra (3 plants)","Meta-Constellation (Clinton)","Microsoft-Constellation (TMI)","Google-NextEra (Duane Arnold)","CyrusOne-Constellation (Freestone)","Meta-TerraPower/Oklo (SMR future)"],"data":[2609,1100,835,615,380,3000],"colors":["#A142F4CC","#A142F4AA","#4C8BF5CC","#34A853CC","#24C1E0CC","#E8548C80"],"indexAxis":"y","x_title":"Megawatts (MW)"},
        "sic_market":{"type":"doughnut","title":"SiC Power Electronics Market Share (%)","source":"Source: Industry estimates, company reports (2025)","labels":["STMicroelectronics (35%)","onsemi (25%)","Infineon (15%)","Wolfspeed (11%)","Others (14%)"],"data":[35,25,15,11,14],"colors":["#4C8BF5CC","#34A853CC","#F9AB00CC","#A142F4CC","#9E9E9ECC"],"cutout":"55%"},
        "lead_times":{"type":"bar","title":"Equipment Lead Times (Weeks) - 2025/2026","source":"Source: Wood Mackenzie, NEMA, industry surveys","labels":["Generator Step-Up Transformers","Power Transformers","Pad-Mount Transformers","Gas Turbines (large frame)","Switchgear (HV)","BESS Systems"],"data":[144,128,78,156,52,36],"colors":["#EA4335CC","#EA4335AA","#F9AB00CC","#F9AB00AA","#4C8BF5CC","#34A853CC"],"y_title":"Weeks"},
        "nuclear_timeline":{"type":"bar","title":"Nuclear / SMR / Fusion - Expected Commercial Deployment Timeline","source":"Source: Company announcements, NRC filings, analyst estimates.","full_width":True,"labels":["Last Energy (Wales PWR)","Oklo (Aurora, INL)","TerraPower (Natrium, WY)","NuScale (new site TBD)","X-energy (Xe-100 demo)","Kairos Power (Hermes)","CFS - SPARC (net power demo)","CFS - ARC (commercial)","Helion - Orion (Microsoft PPA)"],"datasets":[{"label":"Construction / Dev","data":[2026,2026,2025,2027,2026,2024,2024,2028,2025],"color":"#4C8BF580"},{"label":"First Power Target","data":[2027,2028,2031,2030,2029,2030,2027,2032,2028],"color":"#34A853CC"}],"indexAxis":"y","x_min":2024,"x_max":2034,"x_title":"Year"},
        "supply_demand_gap":{"type":"line","title":"Supply vs Demand Gap - US Datacenter Power (GW Estimate)","source":"Source: Goldman Sachs, IEA, company announcements.","full_width":True,"labels":["2024","2025","2026E","2027E","2028E","2029E","2030E"],"datasets":[{"label":"Projected DC Power Demand (GW)","data":[62,80,92,110,130,145,165],"color":"#EA4335","fill":True,"tension":0.3,"borderWidth":3},{"label":"Estimated Available Supply (GW)","data":[60,72,82,95,115,135,155],"color":"#34A853","fill":True,"tension":0.3,"borderWidth":3},{"label":"Supply Gap (GW)","data":[2,8,10,15,15,10,10],"color":"#F9AB00","fill":False,"tension":0.3,"borderWidth":2,"borderDash":[5,5]}],"y_title":"Gigawatts (GW)","y_begin_zero":True}
    })
    print("Seeded: chart_data")

    save("news_briefs", [{"date":"2026-04-23","top_headlines":"IEA: DC electricity to triple by 2030 | Google TPU v8 dual-track chips | Oracle-Bloom 2.8 GW fuel cell deal | Record $300B VC quarter | FERC interconnection delayed to June","sectors":["Energy","Hardware","Finance","Policy"],"tickers":[{"ticker":"SMCI","direction":"neutral","note":""},{"ticker":"SMR","direction":"up","note":"up 16%"},{"ticker":"BE","direction":"up","note":"up 22%"},{"ticker":"PLTR","direction":"down","note":"warning"}],"signals":[{"ticker":"SMCI","signal":"undervalued"},{"ticker":"PLTR","signal":"overvalued"}],"file":"morning-news/2026-04-23.html"}])
    save("valuation_history", [])
    save("analyst_changes", [])
    save("watchlist_signals", [])
    print("Seeded: news_briefs, valuation_history, analyst_changes, watchlist_signals")

    print("\nAll JSON data files seeded:")
    for f in sorted(os.listdir(DATA_DIR)):
        sz = os.path.getsize(os.path.join(DATA_DIR, f))
        print(f"  {f} ({sz:,} bytes)")

if __name__ == "__main__":
    seed()
